In [2]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline
import numpy as np
from decimal import *
from scipy.io import loadmat

In [3]:
df = pd.read_csv("flu.csv")

In [4]:
df.head()

ZIP Code  Ward  Police District   Latitude  Longitude
0     60608  25.0             10.0  41.852187 -87.667757
1     60647   1.0             14.0  41.910411 -87.688899
2     60601  42.0              1.0  41.885491 -87.630822
3     60649   5.0              3.0  41.765816 -87.576145
4     60615   4.0              2.0  41.795297 -87.587823

In [5]:
df.dropna()

ZIP Code  Ward  Police District   Latitude  Longitude
0        60608  25.0             10.0  41.852187 -87.667757
1        60647   1.0             14.0  41.910411 -87.688899
2        60601  42.0              1.0  41.885491 -87.630822
3        60649   5.0              3.0  41.765816 -87.576145
4        60615   4.0              2.0  41.795297 -87.587823
...        ...   ...              ...        ...        ...
1052     60611  42.0             18.0  41.896411 -87.624133
1053     60643  19.0             22.0  41.721083 -87.664186
1054     60614  44.0             19.0  41.932848 -87.648170
1055     60639  31.0             25.0  41.931521 -87.755613
1056     60620  18.0              6.0  41.736501 -87.663228

[1049 rows x 5 columns]

In [10]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.fillna(999, inplace=True)

In [11]:
from sklearn.cluster import KMeans

In [12]:
kmeans = KMeans(n_clusters=4)

In [13]:
kmeans.fit(df.drop('ZIP Code',axis=1))

KMeans(n_clusters=4)

In [14]:
kmeans.cluster_centers_

array([[ 39.29753521,  17.18133803,  41.92858881, -87.69497594],
       [999.        , 999.        ,  41.82483076, -87.68501528],
       [999.        , 999.        , 999.        , 999.        ],
       [ 11.52806653,   7.77754678,  41.79084182, -87.65497625]])

In [15]:
def converter(cluster):
    if cluster=='Yes':
        return 1
    else:
        return 0

In [16]:
df['Cluster'] = df['ZIP Code'].apply(converter)

In [17]:
df

ZIP Code  Ward  Police District   Latitude  Longitude  Cluster
0        60608  25.0             10.0  41.852187 -87.667757        0
1        60647   1.0             14.0  41.910411 -87.688899        0
2        60601  42.0              1.0  41.885491 -87.630822        0
3        60649   5.0              3.0  41.765816 -87.576145        0
4        60615   4.0              2.0  41.795297 -87.587823        0
...        ...   ...              ...        ...        ...      ...
1052     60611  42.0             18.0  41.896411 -87.624133        0
1053     60643  19.0             22.0  41.721083 -87.664186        0
1054     60614  44.0             19.0  41.932848 -87.648170        0
1055     60639  31.0             25.0  41.931521 -87.755613        0
1056     60620  18.0              6.0  41.736501 -87.663228        0

[1057 rows x 6 columns]

In [18]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(df['Cluster'],kmeans.labels_))
print(classification_report(df['Cluster'],kmeans.labels_))

[[569   7   1 480]
 [  0   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]]
              precision    recall  f1-score   support

           0       1.00      0.54      0.70      1057
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

    accuracy                           0.54      1057
   macro avg       0.25      0.13      0.17      1057
weighted avg       1.00      0.54      0.70      1057



C:\Users\Sanaz\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
